on:
  push:
  schedule:
    - cron: '0 0 */1 * *'
  workflow_dispatch:  

name: Test Registry

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: "20.10"
          docker_channel: test
          docker_buildx: false
      - run: docker version
      - run: docker info
      - name: Test
        run: |
          registrys="
          dockerhub.icu
          dockerhub.anzu.vip
          dockerhub.timeweb.cloud
          docker.chenby.cn
          docker.1panel.live
          docker.nastool.de
          docker.agsv.top
          docker.agsvpt.work
          docker.awsl9527.cn
          docker.anyhub.us.kg
          docker.chenby.cn
          docker.diliai.net
          dhub.kubesre.xyz
          docker.m.daocloud.io
          docker.1panel.live
          docker.jijiai.cn
          docker.io
          registry-1.docker.io
          registry.hub.docker.com
          mirror.baidubce.com
          hub-mirror.c.163.com
          docker.mirrors.ustc.edu.cn
          mirror.gcr.io
          dockerproxy.com
          hub.docker.com
          mirror.ccs.tencentyun.com
          mirrors.huaweicloud.com
          $ALIYUN_MIRROR/zouhongqiang
          "
          image="nginx"

          for registry in $registrys
          do
             echo ::group::Test $registry/$image
             docker pull $registry/$image \
               && (echo -e "\033[32m$registry is good\033[0m" \
                  ; echo "::warning file=README.md,line=1,col=0::OK [ $registry ] is good") \
               || (echo -e "\033[31m$registry is outdated\033[0m" \
                  ; echo "::error file=README.md,line=1,col=0::X [ $registry ] is outdated")
             docker rmi $registry/$image || true
             echo ::endgroup::
          done
          
          IMAGE=busybox
          MIRROR=https://dockerhub.icu
          NUM_TRIALS=5

          echo "Testing $MIRROR with $IMAGE"

          total_time=0

          for i in $(seq 1 $NUM_TRIALS); do
          echo "Trial $i"
          start_time=$(date +%s.%N)
          docker pull $IMAGE
          end_time=$(date +%s.%N)
          elapsed_time=$(echo "$end_time - $start_time" | bc)
          total_time=$(echo "$total_time + $elapsed_time" | bc)
          docker rmi $IMAGE
          done

          average_time=$(echo "scale=2; $total_time / $NUM_TRIALS" | bc)
          echo "Average pull time: $average_time seconds"
          echo "::warning file=README.md,line=1,col=0::X [ $MIRROR ] is ok")
        env:
          ALIYUN_MIRROR: ${{secrets.ALIYUN_MIRROR}}
